table 'Income Goal'
	lineageTag: 4abc1ca4-1c08-4f9f-84d2-04e066b2f332

	measure 'Total Income' = SUM('Income Goal'[Income Target])
		formatString: 0
		lineageTag: 6966ecc8-2908-4092-b6d4-2b8be6592d4e

	column Month
		dataType: string
		lineageTag: 8401ceb6-dda4-4132-923e-fea5adcbc3e6
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Income Target'
		dataType: int64
		formatString: 0
		lineageTag: 13f431fe-e934-495b-b7e0-29dd772b9272
		summarizeBy: none
		sourceColumn: Income Target

		annotation SummarizationSetBy = Automatic

	partition 'Income Goal' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\User\Desktop\udemy power bi projects\Personal financial Dataset\Dataset.xlsx"), null, true),
				    #"Income Goal_Sheet" = Source{[Item="Income Goal",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Income Goal_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Month", type text}, {"Income Target", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

